apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: sigstore-worker
  namespace: test-sigstore 
spec:
  clusterDeploymentRef:
    name: sigstore 
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 0
